kind: pipeline
type: docker
name: amd64

platform:
  arch: amd64

steps:
  - name: build and publish
    image: plugins/docker
    settings:
      registry: registry.dev.onetask.ai
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "registry.dev.onetask.ai/code-kern-ai/refinery-parent-images"
      tags: ["${DRONE_COMMIT_SHA}-next", "${DRONE_COMMIT_BRANCH}-next"]
      cache_from:
        - "registry.dev.onetask.ai/code-kern-ai/refinery-parent-images:dev-next"
        - "registry.dev.onetask.ai/code-kern-ai/refinery-parent-images:${DRONE_COMMIT_BRANCH}-next"

trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
  - name: build and publish
    image: plugins/docker
    settings:
      registry: registry.dev.onetask.ai
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "registry.dev.onetask.ai/code-kern-ai/refinery-parent-images"
      tags:
        ["${DRONE_COMMIT_SHA}-next-arm64", "${DRONE_COMMIT_BRANCH}-next-arm64"]
      cache_from:
        - "registry.dev.onetask.ai/code-kern-ai/refinery-parent-images:dev-next-arm64"
        - "registry.dev.onetask.ai/code-kern-ai/refinery-parent-images:${DRONE_COMMIT_BRANCH}-next-arm64"

trigger:
  branch:
    - dev
  event:
    - push

---
kind: pipeline
type: docker
name: amd64-dockerhub

platform:
  arch: amd64

steps:
  - name: build and publish
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: "kernai/refinery-parent-images"
      tag: "${DRONE_TAG}-next-drone-amd64"

trigger:
  event:
    - tag

---
kind: pipeline
type: docker
name: arm64-dockerhub

platform:
  arch: arm64

steps:
  - name: build and publish
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: "kernai/refinery-parent-images"
      tag: "${DRONE_TAG}-next-drone-arm64"

trigger:
  event:
    - tag

---
kind: pipeline
name: manifest
steps:
  - name: manifest
    image: plugins/manifest
    settings:
      spec: manifest.tmpl
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password

depends_on:
  - amd64-dockerhub
  - arm64-dockerhub

trigger:
  event:
    - tag
